### ISSUE TITLE
引入rosetta出现了一些报错

### ISSUE THREAD

**Issue by lexoops** [molingyu/Rosetta#2]
![IUVQG7_1EF%VGHKW4~PU0QS](https://user-images.githubusercontent.com/33716494/179679066-014dc2d1-f74d-483c-9a07-81475b6558ba.png)
您好，按照md文档导入进入工程一直在报错。
我首先将I18N移动到了和Assets同级，然后导入了unitypackage；请问怎么解决如上这些错误？

**Comment by lexoops** [comment]
您好，补充一下。我是导入的rosetta的使用案例，就是百度云的那个案例

**Comment by shitake2333** [comment]
unity version 问题

还有 你有没有导入 Odin Inspector 这个插件

**Comment by lexoops** [comment]
> 
ok,搞定，谢谢
